runtime: custom
env: flex


# https://stackoverflow.com/questions/47125661/pricing-of-google-app-engine-flexible-env-a-500-lesson
# This is a horrible workaround to get streamlit working on app engine
# https://discuss.streamlit.io/t/has-anyone-deployed-to-google-cloud-platform/931/20
# gcloud app deploy app.yaml --version cache-image --promote --stop-previous-version

# entrypoint: find /usr/local/lib/python3.7/site-packages/streamlit -type f \( -iname \*.py -o -iname \*.js \) -print0 | xargs -0 sed -i 's/healthz/health-check/g' && streamlit run app.py --server.port=8080 --server.address=0.0.0.0

# runtime_config:
#   python_version: 3

# manual_scaling:
#   instances: 1

# network:
#   session_affinity: true